<?php

namespace AppBundle\Repository;

/**
 * AbstractImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbstractImageRepository extends \Doctrine\ORM\EntityRepository
{
}
