<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * Class BasketRepository
 * @package AppBundle\Repository
 */
class BasketRepository extends EntityRepository
{
    /**
     * Find not empty basket items
     *
     * @return mixed
     */
    public function findDontEmpty()
    {
        return $this
            ->createQueryBuilder('b')
            ->where('b.products', 0)
            ->getQuery()
            ->getResult();
    }
}
