<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;

/**
 * FeedbackImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedbackImageRepository extends EntityRepository
{
    public function findByFeedback($feedback)
    {
        return $this
            ->createQueryBuilder('i')
            ->where('feedback', ':feedback')
            ->setParameter('feedback', $feedback)
            ->getQuery()
            ->getResult();
    }
}