<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;

/**
 * FeedbackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedbackRepository extends EntityRepository
{
    /**
     * @param int $page
     * @param int $theNumberOnThePage
     * @return mixed
     */
    public function findByPage(int $page, int $theNumberOnThePage)
    {
        $lastResult  = $page * $theNumberOnThePage;
        $firstResult = $lastResult - $theNumberOnThePage;

        return $this
            ->createQueryBuilder('f')
            ->setFirstResult($firstResult)
            ->setMaxResults($theNumberOnThePage)
            ->orderBy('f.created', 'DESC')
            ->getQuery()
            ->getResult();
    }

    /**
     * Quantity all feedbacks
     *
     * @return mixed
     * @throws NonUniqueResultException
     */
    public function getTheQuantityOfAllFeedbacks()
    {
        return $this
            ->createQueryBuilder('f')
            ->select('count(f.id)')
            ->getQuery()
            ->getSingleScalarResult();
    }
}
