<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;

/**
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * Class FeedbackImageRepository
 * @package AppBundle\Repository
 */
class FeedbackImageRepository extends EntityRepository
{
    /**
     * Find feedback image by entity feedback
     *
     * @param $feedback
     * @return mixed
     */
    public function findByFeedback($feedback)
    {
        return $this
            ->createQueryBuilder('i')
            ->where('feedback', ':feedback')
            ->setParameter('feedback', $feedback)
            ->getQuery()
            ->getResult();
    }
}