<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Category;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    /**
     * Find all active products
     *
     * @return mixed
     */
    public function findActive()
    {
        return $this
            ->createQueryBuilder('p')
            ->join('p.category', 'c')
            ->where('p.active = :active')
            ->andWhere('c.active = :active')
            ->setParameter('active', 1)
            ->getQuery()
            ->getResult();
    }

    /**
     * Find product by category
     *
     * @param Category $category
     * @return mixed
     */
    public function findByCategory(Category $category, $page = 1, $theNumberOnThePage = 10)
    {
        $lastResult = $page * $theNumberOnThePage;
        $firstResult = $lastResult - $theNumberOnThePage;

        return $this
            ->createQueryBuilder('p')
            ->where('p.category = :category')
            ->setParameter('category', $category)
            ->setFirstResult($firstResult)
            ->setMaxResults($theNumberOnThePage)
            ->getQuery()
            ->getResult();
    }

    /**
     * @param $page
     * @param $theNumberOnThePage
     * @return mixed
     */
    public function findByPage($page, $theNumberOnThePage)
    {
        $lastResult = $page * $theNumberOnThePage;
        $firstResult = $lastResult - $theNumberOnThePage;

        return $this
            ->createQueryBuilder('p')
            ->setFirstResult($firstResult)
            ->setMaxResults($theNumberOnThePage)
            ->getQuery()
            ->getResult();
    }

    /**
     * @param array $where
     * @return mixed
     * @throws NonUniqueResultException
     */
    public function getTheQuantityOfAllProducts(array $where = null)
    {
        if($where == null){
            return $this
                ->createQueryBuilder('p')
                ->select('count(p.id)')
                ->getQuery()
                ->getSingleScalarResult();
        } else {
            foreach ($where as $field => $item){
                return $this
                    ->createQueryBuilder('p')
                    ->select('count(p.id)')
                    ->where('p.'.$field.' = :item')
                    ->setParameter('item', $item)
                    ->getQuery()
                    ->getSingleScalarResult();
            }
        }
    }

    /**
     * @return mixed
     */
    public function findByRating(){
        return $this
            ->createQueryBuilder('p')
            ->orderBy('p.rating', 'DESC')
            ->getQuery()
            ->getResult();
    }

    /**
     * @return mixed
     */
    public function findBestProducts(){
        return $this
            ->createQueryBuilder('p')
            ->setFirstResult(0)
            ->setMaxResults(10)
            ->orderBy('p.rating', 'DESC')
            ->getQuery()
            ->getResult();
    }

    public function findBySortAndPage(array $sort, $page, $theNumberOnThePage)
    {
        $lastResult = $page * $theNumberOnThePage;
        $firstResult = $lastResult - $theNumberOnThePage;

        foreach($sort as $field => $order){
            return $this
                ->createQueryBuilder('p')
                ->orderBy('p.'.lcfirst($field), $order)
                ->setFirstResult($firstResult)
                ->setMaxResults($theNumberOnThePage)
                ->getQuery()
                ->getResult();
        }
    }
}
