<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ShopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopRepository extends EntityRepository
{
    /**
     * @param $centerLat
     * @param $centerLon
     * @param $radius
     * @return mixed
     */
    public function findToASpecifiedRadius($centerLat, $centerLon, $radius)
    {
        $R = 6371;  // earth's mean radius, km

        $parameters = [
            'lat'    => deg2rad($centerLat),
            'lon'    => deg2rad($centerLon),
            'rad'    => $radius,
            'R'      => $R,
        ];

        return $this->createQueryBuilder('s')
            ->select('s as shop')
            ->addSelect(
                'acos(sin(:lat)*sin(radians(s.lat)) +
                 cos(:lat)*cos(radians(s.lat))*cos(radians(s.lon)-:lon)) *
                  :R As distance'
            )
            ->where("acos(sin(:lat)*sin(radians(s.lat))
             + cos(:lat)*cos(radians(s.lat))*cos(radians(s.lon)-:lon)) * :R < :rad")
            ->orderBy('distance', 'ASC')
            ->setParameters($parameters)
            ->getQuery()
            ->getResult();
    }
}
