# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
        encoders:
            FOS\UserBundle\Model\UserInterface: bcrypt

        role_hierarchy:
            ROLE_ADMIN:       ROLE_USER
            ROLE_SUPER_ADMIN: ROLE_ADMIN

        providers:
            fos_userbundle:
                id: fos_user.user_provider.username_email
            api_user_provider:
                id: AppBundle\Security\User\ApiUserProvider

        firewalls:
            main:
                pattern: ^/
                form_login:
                    provider: fos_userbundle
                    csrf_token_generator: security.csrf.token_manager
                    login_path: fos_user_security_login
                    check_path: fos_user_security_check
                    success_handler: app.authentication_success_handler
                logout:
                  path: fos_user_security_logout
                  target: /
                anonymous: true
            api:
                pattern: ^/api/
                stateless: true
                simple_preauth:
                  authenticator: AppBundle\Security\TokenAuthenticator
                provider: api_user_provider


        access_control:
            - { path: ^/user/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/user/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/user/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/admin/, role: ROLE_ADMIN }
            - { path: ^/product, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/category, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/user/profile/, role: ROLE_USER }
            - { path: ^/basket/, role: ROLE_USER }
            - { path: ^/product/add-to-basket/, role: ROLE_USER }
#            - { path: ^/api, roles: ROLE_USER }
