# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
        encoders:
            FOS\UserBundle\Model\UserInterface: bcrypt

        role_hierarchy:
            ROLE_ADMIN:       ROLE_USER
            ROLE_SUPER_ADMIN: ROLE_ADMIN

        providers:
            chain_provider:
                chain:
                  providers: [fos_userbundle, api_user_provider]
            fos_userbundle:
                id: fos_user.user_provider.username_email
            api_user_provider:
                id: api_user_provider

        firewalls:
            login:
                pattern:  ^/api/login
                stateless: true
                anonymous: true
                json_login:
                    check_path:               /api/login_check
                    success_handler:          lexik_jwt_authentication.handler.authentication_success
                    failure_handler:          lexik_jwt_authentication.handler.authentication_failure
            api:
                anonymous: ~
                pattern:   ^/api
                stateless: true
                guard:
                    authenticators:
                        - lexik_jwt_authentication.jwt_token_authenticator
            main:
                pattern: ^/
                form_login:
                    provider: fos_userbundle
                    csrf_token_generator: security.csrf.token_manager
                    login_path: fos_user_security_login
                    check_path: fos_user_security_check
                    success_handler: app.authentication_success_handler
                logout:
                  path: fos_user_security_logout
                  target: /
                anonymous: true

        access_control:
            - { path: ^/user/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/user/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/user/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/admin/, role: ROLE_ADMIN }
            - { path: ^/product, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/category, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/user/profile/, role: ROLE_USER }
            - { path: ^/basket/, role: ROLE_USER }
            - { path: ^/product/add-to-basket/, role: ROLE_USER }
            - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/api/get-token, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/api/doc, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
